name: sharer_app
description: "Sharer App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.5
  process_run: ^1.2.2+1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
